### ISSUE TITLE
Doesn't seem to work when you have external dependencies

### ISSUE THREAD

**Issue by samlobel** [dldl/sphinx-preview#10]
My docs use the rtd_theme. I'm thinking my problem is that the package isn't installed in the docker container. Does that sound right? I'm 404-ing, but can build locally when I'm in a virtualenv with the right dependencies.

Thanks

**Comment by quentinus95** [comment]
Hi,

The used Dockerfile does include rtd_theme: https://github.com/dldl/sphinx-server/blob/master/Dockerfile

You may check the issue #7 as it may contain some clues about the issue. Sadly I don't have time to fix it but feel free to open a PR!

**Comment by quentinus95** [comment]
This may have been fixed in #15 & #16. Please re-open the issue otherwise.
