### ISSUE TITLE
connection problem while opening

### ISSUE THREAD

**Issue by iUtsavB** [dldl/sphinx-preview#12]
error showing : connect ECONNREFUSED 127.0.0.1:2375

**Comment by quentinus95** [comment]
Sphinx-Server listens on the `8000` port. Can you provide more context?

**Comment by quentinus95** [comment]
@iUtsavB some changes in port mapping have been recently done in Sphinx-Server. Can you try with the latest version of the image?

**Comment by quentinus95** [comment]
Closing as no answer from author.
