### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by quentinus95** [dldl/sphinx-preview#2]
Cache issue on Ubuntu 16.10 ; page is refreshing but changes are not shown.

**Comment by quentinus95** [comment]
Temporary fixed using DevTools.

![image](https://cloud.githubusercontent.com/assets/8060564/22585955/a6edb052-e9fa-11e6-9923-475866685958.png)

**Comment by andreycizov** [comment]
It also works on my Firefox if I open the window in parallel.

**Comment by hileef** [comment]
Working on it, see lepture/python-livereload#183

**Comment by andreycizov** [comment]
Alternative fix now merged by lepture: https://github.com/lepture/python-livereload/pull/192 Can you guys check if that works for you?

**Comment by quentinus95** [comment]
When lepture releases a new version on pypi, I'll generate a new docker image.

**Comment by quentinus95** [comment]
New image of sphinx-server has been generated.
